### ISSUE TITLE
[Feature Request] Custom Help hide absent cog names 

### ISSUE THREAD

**Issue by Merp-Me** [npc203/npc-cogs#18]
Ability to refresh everything. Currently, when you unload a cog, it still stays on the help menu on the main bit. This would also remove those cogs that are not loaded from the help menu making it look less crowded and will no longer show cogs that are unloaded.
<img width="436" alt="image" src="https://user-images.githubusercontent.com/64408204/120669042-fcbf7680-c486-11eb-8aa1-2411df525fd3.png">
<img width="404" alt="image" src="https://user-images.githubusercontent.com/64408204/120669375-4e680100-c487-11eb-9dd5-6eb9fa4accad.png">

**Comment by npc203** [comment]
This is one such major bug where no one complained so I just assumed ppl didn't care.
The problem is Red doesn't tell you when a cog is unloaded or uninstalled. So the cog still remains in the cache unfortunately. 
This only affects the "main" feature of a specific theme as shown in screenshot. The cog help won't be shown if u go into the category.

A cog unload listener is planned, will fix sooner or later.
Meanwhile a hotfix is manually removing the cog using `[p]chelp remove cog CogName`.

**Comment by npc203** [comment]
Resolved this in the dpy2 branch, will be imposed whenever red 3.5 version comes out.
