### ISSUE TITLE
[Feature Request] Snipe Attachments

### ISSUE THREAD

**Issue by Honkertonken** [npc203/npc-cogs#47]
In the snipe cog add a way to snipe images/ attachments. (snipe attachments bulk would be cool too.)

**Comment by JeffJrShim** [comment]
-1
What if you're sniping stuff that are ToS breaking? That will cause your bot to be liable.

**Comment by Honkertonken** [comment]
> -1 What if you're sniping stuff that are ToS breaking? That will cause your bot to be liable.

if that's the case then you shouldn't really use this cog  at all cause even messages/ embeds which are tos breaking can be sniped.

**Comment by npc203** [comment]
hmm,
1) technically everything's stored in RAM, nothing's persisted and thus a restart or reload would suffice to delete all the data the cog has, so it isn't exactly TOS breaking, more of a fair game ~ grey lines.

2) Recording attachments is only possible by reuploading the whole attachement to memory (RAM) which is disasterous to the bot. Discord deletes the attachment within a few hours of message deletion, soo storing the url of the attachment goes in vain as well, BUT it could be helpful for those few hrs, then again idk

**Comment by TwinDragon** [comment]
I'm gonna say not interested in this for the liability reasons mentioned above. I don't really use the cog since I already have one that tracks deleted messages in a log channel, but it has been stated a few times by a few people.

If someone posts an image that is clearly illegal, and the bot is saving it in some form to post, that can open up the bot owner to legal trouble and get the bot terminated as well as the owner. Not to mention it would be very easy to slow the bot down by filling up the RAM and swap (if on Linux) and possibly just causing the OS to crash due to running out of memory.

**Comment by npc203** [comment]
Will add the attachment url, when sniped, at some point.
Not reuploading or storing the actual byte data anywhere in the VPS
